import Head from 'next/head'

export default function Home() {
  return (
    <>
      <Head>
        <title>로그인 | INTOUCH CHURCH</title>
        <meta name="description" content="Generated by create next app" />
      </Head>
      <main>
        <h1>INTOUCH</h1>
      </main>
    </>
  )
}
