query findUserCellTransferRegister(
  $limit: Int
  $id: Float!
  $transferOutStatus: [UserCellTransferStatus!]
  $transferOutDateFilter: DateFilter
) {
  findCells(limit: $limit) {
    nodes {
      id
      name
    }
  }
  findCell(id: $id) {
    members {
      id
      name
      gender
      grade
      birthday
      phone
      isActive
      roles
    }
    transfersOut(
      status: $transferOutStatus
      orderDate: $transferOutDateFilter
    ) {
      id
      status
      user {
        id
        name
        gender
      }
      fromCell {
        id
        name
      }
      toCell {
        id
        name
      }
    }
  }
}
